services:
  backend:
    build: ./backend
    container_name: nerdsite-backend
    restart: always
    ports:
      - '5001:5000'
    environment:
      - JWT_SECRET=your_super_secret_key
      - NODE_ENV=development
      - PORT=5000
      - USE_JSON_DB=true
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build: .
    container_name: nerdsite-frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

